version: "3"

services:
  datastore:
    image: postgres:latest
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: datastore
      POSTGRES_PASSWORD: datastore

  shell:
    build: .
    command: /bin/bash
    environment:
      DATASTORE_URI: postgresql://datastore:datastore@datastore/datastore
    links:
      - datastore
    volumes:
      - "./src:/src"
    tmpfs:
      - "/tmp" 
  
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - "./:/home/jovyan/work/"
    environment:
      JUPYTER_TOKEN: docker

volumes:
  postgres: {}
