version: "3"

services:
  jupyter:
    build: .
    ports:
      - 8888:8888
    volumes:
      - "./:/home/jovyan/work/"
      - "/Users/dt/dimitri.tokmetzis@ftm.nl - Google Drive/My Drive/Projecten/north_sea_data/:/home/jovyan/work/drive/"
    environment:
      JUPYTER_TOKEN: docker

