

datasets:
  events:
    fishing: 'public-global-fishing-events:latest'
    encounters: 'public-global-encounters-events:latest'
    loitering: 'public-global-loitering-events-carriers:latest'
    ports: 'public-global-port-visits-c2-events:latest'
  vessels:
    fishing: 'public-global-fishing-vessels:latest'
    carrier: 'public-global-carrier-vessels:latest'
    support: 'public-global-support-vessels:latest'
end_points:
  vessels: 'https://gateway.api.globalfishingwatch.org/v2/vessels

